[book]
authors = ["r1Way"]
language = "en"
multilingual = false
src = "src"
title = "know"
[output.html]
additional-js = ["assets/fzf.umd.js", "assets/elasticlunr.js"]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]